# Generated by Django 4.0.3 on 2022-03-16 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_post', models.CharField(max_length=255, verbose_name='título')),
                ('data_post', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data')),
                ('conteudo_post', models.TextField(verbose_name='conteúdo')),
                ('excerto_post', models.TextField(verbose_name='excerto')),
                ('imagem_post', models.ImageField(blank=True, null=True, upload_to='post_img/%Y/%m/%d', verbose_name='imagem')),
                ('publicado_post', models.BooleanField(default=False, verbose_name='publicado')),
                ('autor_post', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='post_user', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('categoria_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='post_categoria', to='categorias.categoria', verbose_name='categoria')),
            ],
        ),
    ]
