# Generated by Django 4.0.3 on 2022-03-16 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_comentario', models.CharField(max_length=255, verbose_name='nome')),
                ('email_comentario', models.EmailField(max_length=254, verbose_name='email')),
                ('comentario', models.TextField(verbose_name='comentario')),
                ('data_comentario', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data')),
                ('publicado_comentario', models.BooleanField(default=False, verbose_name='publicado')),
                ('post_comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentario_post', to='posts.post', verbose_name='post')),
                ('usuario_comentario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comentario_user', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
        ),
    ]
