# Generated by Django 4.0.3 on 2022-03-16 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('comentarios', '0002_alter_comentario_usuario_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='post_comentario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post', verbose_name='post'),
        ),
    ]
